### ISSUE TITLE
oddaja projekta

### ISSUE THREAD

**Issue by majcufer** [majcufer/Marina-Management#2]
Živjo,
projekt je zaključen, vključno z delujočim binderjem.

Lp, Maj

**Comment by gasperxy** [comment]
Živjo,

Aplikacija izgleda zelo dobro. Držal si se navodil, ki sem jih povedal prav tako pa je tudi vizualno kar lepo urejena.
Opazil sem samo eno težavo in sicer v Binderju ne deluje iskalnik na prvi strani in to zato, ker imaš v index.html datoteki na formi `action` uporabljen brez `url()` funkcije. To še spremeni in naloži novo verzijo.

Še en manjši komentar pa bi imel mogoče glede metode iskanje v app.py datoteki. Tam uporabljaš neke konverzije v int podatkovne tipe ter potem neke if stavke in podobno. Sicer je vse ok, ampak taka koda ponavadi bolj sodi v service layer.  Tega ni potrebno popravljat.

Ko popraviš še to malenkost zgoraj je projekt iz moje strani odobren. 
@jaanos

Lp,
Gašper
